import "../styles/globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";

import NextTopLoader from "nextjs-toploader";
import { Analytics } from "@vercel/analytics/react";

import { Suspense } from "react";
import Nav from "@/components/ui/nav";
import Footer from "@/components/footer/footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description:
    "Generated by create next app. Focused on storing different exercises. What exercises? simple exercises that could be asked during some kind of interview or just to simply stimulate the knowledge.",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body className="bg-gray-1100 overflow-y-scroll pb-20">
        <NextTopLoader showSpinner={false} />
        <Suspense fallback={<h2>Loading...</h2>}>
          <Nav />
        </Suspense>
        <main className="mx-auto max-w-6xl space-y-4 px-2 pt-16">
          <article className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
            {/* lg:p-4 */}
            <section className="rounded-lg bg-black p-3.5">{children}</section>
          </article>
          <Footer />
        </main>
        <Analytics />
      </body>
    </html>
  );
}
